version: "3.2"
services:
  django: 
    build: 
      context: ./django
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./misc/variables.txt
    ports: 
      - "8000:8000"
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file: ./misc/variables.txt
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    env_file: ./misc/variables.txt
    command: bash -c "/scripts/start.sh"
    ports:
      - "9200:9200"
      - "9300:9300"