version: "3.2"
services:
  django: 
    build: 
      context: ./django
      dockerfile: Dockerfile
    command: bash -c "tail -f /dev/null"
    env_file: ./misc/variables.txt
    ports: 
      - "8000:8000"
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file: ./misc/variables.txt
