version: "3.2"
services:
  django: 
    build: 
      context: ./django
      dockerfile: Dockerfile
    command: gunicorn simssadb.wsgi:application --bind 0.0.0.0:8000
    env_file: ./misc/variables.txt
    expose: 
      - "8000"
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - static_volume:/code/simssadb/static
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file: ./misc/variables.txt
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  elasticsearch:
    image: "elasticsearch:5"
    ports:
      - "9200:9200"
      - "9300:9300"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - "1337:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: