#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

/usr/local/bin/gunicorn --chdir /code/simssadb simssadb.wsgi:application --bind 0.0.0.0:8000
