#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

# Setup the database
python manage.py flush --no-input
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --no-input
  # Adding Sample Data to the database
cd sample_data
cd madrigal
./add_all.sh
cd ..
cd ..

# Bring up gunicorn
/usr/local/bin/gunicorn --chdir /code/simssadb simssadb.wsgi:application --bind 0.0.0.0:8000 --timeout 300
